"""Central configuration values for the Real-Time AI Air Canvas application."""

WINDOW_NAME = "Real-Time AI Air Canvas"

# Camera
CAMERA_INDEX = 0
CAMERA_FALLBACK_INDEXES = (0, 1, 2)
CAMERA_BACKEND = 0
FRAME_WIDTH = 1920
FRAME_HEIGHT = 1080
DEFAULT_MIRROR_FRAME = True
MAX_CAMERA_READ_FAILURES = 15
START_IN_FULLSCREEN = True

# MediaPipe
HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.72
MAX_NUM_HANDS = 1
DRAW_LANDMARKS_BY_DEFAULT = True
LANDMARK_CONNECTION_COLOR = (80, 180, 220)
LANDMARK_POINT_COLOR = (255, 220, 120)
LANDMARK_CONNECTION_THICKNESS = 2
LANDMARK_POINT_RADIUS = 2
HAND_MODEL_COMPLEXITY = 1
LANDMARK_SMOOTHING_ALPHA = 0.45
LANDMARK_MAX_JUMP_FACTOR = 1.1

# Cursor
CURSOR_RADIUS = 10
CURSOR_FILL_RADIUS = 4
CURSOR_THICKNESS = 2
CURSOR_ERASER_RADIUS = 16
CURSOR_COLOR = (255, 255, 255)
CURSOR_ACTIVE_COLOR = (0, 255, 255)

# Palette
PALETTE_HEIGHT = 82
PALETTE_MARGIN = 14
PALETTE_BOX_WIDTH = 120
PALETTE_BOX_HEIGHT = 48
PALETTE_TEXT_SCALE = 0.6
PALETTE_HOVER_TIME = 0.35
PALETTE_HIT_INSET = 10
PALETTE_COOLDOWN = 0.45
PALETTE_LABEL_Y_OFFSET = 31

# Drawing
BACKGROUND_COLOR = (0, 0, 0)
DRAW_THICKNESS = 6
MIN_BRUSH_THICKNESS = 2
MAX_BRUSH_THICKNESS = 24
BRUSH_STEP = 2
ERASER_THICKNESS = 30
MIN_ERASER_THICKNESS = 8
MAX_ERASER_THICKNESS = 50
SMOOTHING_WINDOW = 6
SMOOTHING_ALPHA = 0.38
DRAW_DEADZONE_PIXELS = 4
INTERPOLATION_STEPS = 6
FAST_MOVEMENT_DISTANCE = 34
FAST_INTERPOLATION_STEPS = 12
MIN_STROKE_POINTS = 2
ERASER_COLOR_NAME = "black"

# Gesture timing
ERASER_TOGGLE_COOLDOWN = 1.0
CLEAR_COOLDOWN = 1.2
ERASER_HOLD_TIME = 0.45
CLEAR_HOLD_TIME = 0.6

# UI
SHOW_HELP_BY_DEFAULT = True
SHOW_FPS_BY_DEFAULT = True
STATUS_PANEL_X = 16
STATUS_PANEL_Y = 104
STATUS_PANEL_WIDTH = 360
STATUS_PANEL_HEIGHT = 172
STATUS_PANEL_ALPHA = 0.62
MODE_BADGE_WIDTH = 170
MODE_BADGE_HEIGHT = 40
TEXT_COLOR = (245, 245, 245)
TEXT_MUTED_COLOR = (205, 205, 205)
TEXT_ACCENT_COLOR = (90, 220, 255)
TEXT_SCALE = 0.62
TEXT_THICKNESS = 2
HELP_PANEL_X = 16
HELP_PANEL_WIDTH = 470
HELP_PANEL_HEIGHT = 220
TOAST_DURATION_SECONDS = 1.5
TOAST_Y_OFFSET = 36
TOAST_PADDING_X = 16
TOAST_HEIGHT = 36

# Save/export
SAVE_PREFIX = "air_canvas"
COMPOSITE_PREFIX = "air_canvas_composite"
TRANSPARENT_PREFIX = "air_canvas_transparent"

COLOR_MAP = {
    "red": (0, 0, 255),
    "green": (0, 255, 0),
    "blue": (255, 0, 0),
    "yellow": (0, 255, 255),
    "black": (0, 0, 0),
    "white": (255, 255, 255),
}

PALETTE_ORDER = ["red", "green", "blue", "yellow", "black"]

FINGERTIP_IDS = {
    "thumb": 4,
    "index": 8,
    "middle": 12,
    "ring": 16,
    "pinky": 20,
}

FINGER_PIP_IDS = {
    "thumb": 3,
    "index": 6,
    "middle": 10,
    "ring": 14,
    "pinky": 18,
}

FINGER_MCP_IDS = {
    "thumb": 2,
    "index": 5,
    "middle": 9,
    "ring": 13,
    "pinky": 17,
}

INDEX_FINGER_NAME = "index"
